#!/usr/bin/env python3
"""Helper for tools/latexdiff.sh.

Two jobs, both about making latexdiff play nicely with a paper's
todonotes wrapper macros (\\alice{}, \\bob{}, \\carol{}, ... — anything
defined as \\newcommand{\\name}[2][]{\\note[#1]{label}{color}{#2}} in
macros.tex or main.tex, plus its capitalized \\newcommand{\\Name}[2][]{
\\name[inline,#1]{#2}...} inline variant):

  discover TEX_DIR --names-out NAMES --macros-out MACROS
      Scans every *.tex file in TEX_DIR for note-wrapper macro
      definitions and writes:
        NAMES:   a comma-separated list of the macro names found, for
                 latexdiff's --append-context1cmd.
        MACROS:  \\newcommand{\\<name>del}[2][]{...} definitions, one per
                 discovered macro, that render a REMOVED note as a gray
                 struck-through todo bubble instead of a normal one.
      This has to be discovered rather than hardcoded because the
      wrapping-in-\\DIFdel trick latexdiff normally uses for a fully
      deleted command breaks todonotes: \\DIFdel wraps its argument in
      ulem's \\sout, which boxes its content, and todonotes' \\todo calls
      \\marginpar internally, which cannot run inside a box ("not in
      outer par mode" / pgfkeys errors). So instead we tell latexdiff to
      treat these as --append-context1cmd, which disables the command in
      deleted spans and hands back its argument as plain \\DIFdel text;
      `rewrite` below turns that back into a call to the *del variant,
      which puts \\sout only around the note's inner text (safe).

  rewrite DIFF_TEX --names-file NAMES
      Rewrites the latexdiff output DIFF_TEX in place, turning each
        %DIFDELCMD < \\name{% {%DIFAUXCMD \\DIFdel{TEXT}} %DIFAUXCMD
      latexdiff emits for a fully deleted note into
        \\namedel{TEXT}
      so it renders as the gray struck-through bubble defined by the
      corresponding macro from `discover`.
"""
import argparse
import re
import sys
from pathlib import Path

NOTE_BASE_RE = re.compile(
    r"\\newcommand\{\\(?P<name>[A-Za-z]+)\}\[2\]\[\]\{"
    r"\\note\[#1\]\{(?P<label>[^{}]*)\}\{(?P<color>[^{}]*)\}\{#2\}\}"
)
NOTE_INLINE_RE = re.compile(
    r"\\newcommand\{\\(?P<capname>[A-Za-z]+)\}\[2\]\[\]\{"
    r"\\(?P<base>[A-Za-z]+)\[inline,#1\]\{#2\}(?:\\noindentaftertodo)?\}"
)


def discover(tex_dir: Path):
    bases = {}  # name -> (label, color)
    inlines = {}  # capname -> base
    for path in sorted(tex_dir.glob("*.tex")):
        text = path.read_text(encoding="utf-8")
        for m in NOTE_BASE_RE.finditer(text):
            bases[m.group("name")] = (m.group("label"), m.group("color"))
        for m in NOTE_INLINE_RE.finditer(text):
            inlines[m.group("capname")] = m.group("base")
    # only keep inline variants whose base note macro was actually found
    inlines = {cap: base for cap, base in inlines.items() if base in bases}
    return bases, inlines


def macro_block(bases, inlines):
    lines = [
        "% latexdiff-only: render a removed author note as a gray",
        "% struck-through bubble instead of silently dropping it.",
        "% Generated by tools/latexdiff_notes.py, do not hand-edit.",
        # A reconstructed deleted note may still contain a \response{...}
        # reply-thread call (macros.tex: \vspace{3pt}\hrule\vspace{3pt}\textbf{#1: }).
        # \sout (ulem) typesets its argument as a horizontal box, and \hrule/\vspace
        # are vertical-mode commands that cannot run inside one ("You can't use
        # `\hrule' here except with leaders"), so swap in an inline-safe variant
        # for the duration of the struck-through text.
        r"\newcommand{\responseinline}[1]{\textbf{#1: }}",
    ]
    for name, (label, _color) in sorted(bases.items()):
        lines.append(
            r"\newcommand{\%sdel}[2][]{\note[#1]{%s, removed}{gray!30}"
            r"{{\let\response\responseinline\sout{#2}}}}" % (name, label)
        )
    for cap, base in sorted(inlines.items()):
        lines.append(r"\newcommand{\%sdel}[2][]{\%sdel[inline,#1]{#2}}" % (cap, base))
    return "\n".join(lines) + "\n"


def cmd_discover(args):
    bases, inlines = discover(Path(args.tex_dir))
    names = sorted(set(bases) | set(inlines))
    Path(args.names_out).write_text(",".join(names), encoding="utf-8")
    Path(args.macros_out).write_text(macro_block(bases, inlines), encoding="utf-8")
    print(
        "discovered %d note macro(s): %s" % (len(names), ", ".join(names) or "(none)"),
        file=sys.stderr,
    )


def find_matching_brace(s, start):
    assert s[start] == "{"
    depth = 0
    i = start
    while i < len(s):
        c = s[i]
        if c == "\\" and i + 1 < len(s):
            i += 2
            continue
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    raise ValueError("unbalanced braces from %d" % start)


def extract_note_body(text, open_brace):
    """Reconstruct the plain original text of a fully-deleted note's argument.

    `open_brace` points at the '{' of the '{%DIFAUXCMD ...}' group latexdiff
    emits right after a --append-context1cmd command marker. The group's
    content is not a single flat \\DIFdel{...}: any ordinary command nested
    inside the note (e.g. \\response{...}, \\emph{...}) makes latexdiff
    interleave plain text with \\DIFdel{...} chunks and single-line
    '%DIFDELCMD < CMD %%%' markers. We scan the group tracking brace depth,
    unwrap \\DIFdel{...} to its inner text, drop latexdiff's own '%DIF...'
    scaffolding lines (restoring the commented-out command from
    '%DIFDELCMD < ... %%%' markers), and copy everything else verbatim, to
    splice the note's original (pre-deletion) text back together.

    Returns (body_text, index_just_past_the_matching_%DIFAUXCMD_trailer).
    """
    assert text[open_brace] == "{"
    i = open_brace + 1
    m = re.match(r"%DIFAUXCMD\s*", text[i:])
    if not m:
        raise ValueError("expected %%DIFAUXCMD right after '{' at %d" % open_brace)
    i += m.end()
    pieces = []
    depth = 0
    while True:
        if text[i] == "}" and depth == 0:
            after = i + 1
            m_close = re.match(r"\s*%DIFAUXCMD\s*", text[after:])
            if m_close:
                return "".join(pieces), after + m_close.end()
        m_difdel = re.match(r"\\DIFdel\{", text[i:])
        if m_difdel:
            brace_open = i + m_difdel.end() - 1
            brace_close = find_matching_brace(text, brace_open)
            pieces.append(text[brace_open + 1 : brace_close])
            i = brace_close + 1
            continue
        m_cmd = re.match(r"%DIFDELCMD\s*<\s*(.*?)\s*%%%\r?\n", text[i:])
        if m_cmd:
            pieces.append(m_cmd.group(1))
            i += m_cmd.end()
            continue
        m_aux = re.match(r"%DIF\w*[^\n]*\r?\n", text[i:])
        if m_aux:
            i += m_aux.end()
            continue
        c = text[i]
        if c == "\\" and i + 1 < len(text):
            pieces.append(text[i : i + 2])
            i += 2
            continue
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
        pieces.append(c)
        i += 1


def rewrite(text, names):
    if not names:
        return text, 0
    out = []
    i = 0
    count = 0
    while True:
        best = None
        best_name = None
        best_marker = None
        for name in names:
            marker = "%DIFDELCMD < \\" + name + "{%"
            idx = text.find(marker, i)
            if idx != -1 and (best is None or idx < best):
                best, best_name, best_marker = idx, name, marker
        if best is None:
            out.append(text[i:])
            break
        out.append(text[i:best])
        pos = best + len(best_marker)
        m = re.match(r"\s*(?={%DIFAUXCMD)", text[pos:])
        if not m:
            raise ValueError(
                "unexpected structure after %r at %d: %r"
                % (best_marker, best, text[pos : pos + 80])
            )
        open_brace = pos + m.end()
        inner_text, after = extract_note_body(text, open_brace)
        out.append("\\%sdel{%s}" % (best_name, inner_text))
        i = after
        count += 1
    return "".join(out), count


def cmd_rewrite(args):
    names_text = Path(args.names_file).read_text(encoding="utf-8").strip()
    names = [n for n in names_text.split(",") if n]
    path = Path(args.diff_tex)
    text = path.read_text(encoding="utf-8")
    new_text, count = rewrite(text, names)
    path.write_text(new_text, encoding="utf-8")
    print("rewrote %d removed-note deletion(s)" % count, file=sys.stderr)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="mode", required=True)

    d = sub.add_parser("discover")
    d.add_argument("tex_dir")
    d.add_argument("--names-out", required=True)
    d.add_argument("--macros-out", required=True)
    d.set_defaults(func=cmd_discover)

    r = sub.add_parser("rewrite")
    r.add_argument("diff_tex")
    r.add_argument("--names-file", required=True)
    r.set_defaults(func=cmd_rewrite)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
